import argparse
import csv
import os


def parse_args():
    parser = argparse.ArgumentParser(description="Export real mall recommendation CSV to recommend_result SQL without id remapping.")
    parser.add_argument("--recommendations", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--recommend-type", required=True)
    parser.add_argument("--reason-prefix", default="")
    parser.add_argument("--topn", type=int, default=10)
    return parser.parse_args()


def sql_string(value):
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def main():
    args = parse_args()
    rows = []
    with open(args.recommendations, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get("recommend_type") != args.recommend_type:
                row["recommend_type"] = args.recommend_type
            rows.append(row)

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    rank_by_user = {}
    seen_by_user = {}
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("-- Generated by ml-recommend/export_recommend_sql_direct.py from real mall behavior data\n")
        f.write("USE mall;\n")
        f.write("SET NAMES utf8mb4;\n")
        f.write(f"DELETE FROM recommend_result WHERE recommend_type = {sql_string(args.recommend_type)};\n")
        for row in rows:
            user_id = int(float(row["user_id"]))
            product_id = int(float(row["external_item_id"]))
            seen = seen_by_user.setdefault(user_id, set())
            if product_id in seen:
                continue
            next_rank = rank_by_user.get(user_id, 0) + 1
            if next_rank > args.topn:
                continue
            seen.add(product_id)
            rank_by_user[user_id] = next_rank
            reason = row.get("reason") or ""
            if args.reason_prefix and args.reason_prefix not in reason:
                reason = f"{args.reason_prefix}；{reason}" if reason else args.reason_prefix
            f.write(
                "INSERT INTO recommend_result "
                "(user_id, product_id, recommend_score, rank_no, recommend_type, reason, create_time) VALUES "
                f"({user_id}, {product_id}, {float(row['score']):.6f}, {next_rank}, "
                f"{sql_string(args.recommend_type)}, {sql_string(reason)}, NOW());\n"
            )
    print(f"users={len(rank_by_user)} rows={sum(rank_by_user.values())} output={args.output}")


if __name__ == "__main__":
    main()
