import argparse
import csv
import os


def parse_args():
    parser = argparse.ArgumentParser(description="Export model recommendation CSV to mall-swarm recommend_result SQL.")
    parser.add_argument("--recommendations", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--mall-product-ids", default="26,42,44,45", help="Comma-separated local mall product ids")
    parser.add_argument("--mall-user-ids", default="", help="Comma-separated local mall user ids; defaults to model user ids")
    parser.add_argument("--max-users", type=int, default=30, help="Limit exported users for demo stability")
    parser.add_argument("--recommend-type", default="model_itemcf", help="recommend_result.recommend_type value")
    parser.add_argument("--reason-prefix", default="基于淘宝行为数据训练的 ItemCF 模型推荐", help="Reason prefix shown in dashboard")
    return parser.parse_args()


def sql_string(value):
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def load_recommendations(path, max_users):
    rows = []
    user_order = []
    seen_users = set()
    with open(path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            user_id = row["user_id"]
            if user_id not in seen_users:
                if len(seen_users) >= max_users:
                    continue
                seen_users.add(user_id)
                user_order.append(user_id)
            rows.append(row)
    return rows, user_order


def build_display_scores(rows, user_mapping):
    grouped = {}
    for idx, row in enumerate(rows):
        local_user_id = user_mapping.get(row["user_id"], row["user_id"])
        grouped.setdefault(local_user_id, []).append((idx, row))

    display_scores = {}
    for entries in grouped.values():
        entries.sort(key=lambda item: int(float(item[1].get("rank_no") or 999999)))
        raw_scores = [float(row.get("score") or 0) for _, row in entries]
        min_score = min(raw_scores)
        max_score = max(raw_scores)
        for rank_index, (idx, row) in enumerate(entries):
            if max_score > min_score:
                normalized = (float(row.get("score") or 0) - min_score) / (max_score - min_score)
                display_scores[idx] = 0.60 + normalized * 0.38
            else:
                display_scores[idx] = max(0.70, 0.98 - rank_index * 0.03)
    return display_scores


def main():
    args = parse_args()
    product_ids = [pid.strip() for pid in args.mall_product_ids.split(",") if pid.strip()]
    mall_user_ids = [uid.strip() for uid in args.mall_user_ids.split(",") if uid.strip()]
    if not product_ids:
        raise SystemExit("At least one mall product id is required.")

    rows, user_order = load_recommendations(args.recommendations, args.max_users)
    external_items = []
    for row in rows:
        item_id = row["external_item_id"]
        if item_id not in external_items:
            external_items.append(item_id)
    item_mapping = {item_id: product_ids[idx % len(product_ids)] for idx, item_id in enumerate(external_items)}
    user_mapping = {}
    if mall_user_ids:
        user_mapping = {user_id: mall_user_ids[idx % len(mall_user_ids)] for idx, user_id in enumerate(user_order)}
    display_scores = build_display_scores(rows, user_mapping)

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("-- Generated by ml-recommend/export_recommend_sql.py\n")
        f.write("USE mall;\n")
        f.write("SET NAMES utf8mb4;\n")
        f.write(f"DELETE FROM recommend_result WHERE recommend_type = {sql_string(args.recommend_type)};\n")
        used_products_by_user = {}
        exported_rank_by_user = {}
        for row_idx, row in enumerate(rows):
            local_user_id = user_mapping.get(row["user_id"], row["user_id"])
            used_products = used_products_by_user.setdefault(local_user_id, set())
            preferred_index = external_items.index(row["external_item_id"]) % len(product_ids)
            product_id = None
            for offset in range(len(product_ids)):
                candidate = product_ids[(preferred_index + offset) % len(product_ids)]
                if candidate not in used_products:
                    product_id = candidate
                    break
            if product_id is None:
                continue
            used_products.add(product_id)
            exported_rank_by_user[local_user_id] = exported_rank_by_user.get(local_user_id, 0) + 1
            reason = f"{args.reason_prefix}；{row['reason']}"
            f.write(
                "INSERT INTO recommend_result "
                "(user_id, product_id, recommend_score, rank_no, recommend_type, reason, create_time) VALUES "
                f"({int(local_user_id)}, {int(product_id)}, {display_scores[row_idx]:.6f}, {exported_rank_by_user[local_user_id]}, "
                f"{sql_string(args.recommend_type)}, {sql_string(reason)}, NOW());\n"
            )
    print(f"users={len(user_order)} external_items={len(external_items)} output={args.output}")
    print("mapped_product_ids=" + ",".join(product_ids))
    if mall_user_ids:
        print("mapped_user_ids=" + ",".join(mall_user_ids))
    print("recommend_type=" + args.recommend_type)


if __name__ == "__main__":
    main()
